baseURL = 'https://gxanshu.in'
languageCode = 'en-us'
title = "Gx Anshu: A Showcase of Impressive JavaScript Dev"
Description="gxanshu is a portfolio website showcasing impressive web development projects created by GX Anshu with his expertise in software development and web design."
paginate = 12
[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1