[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/tutorials/create-keyboard-shortcut-in-javascript"
  to = "/blog/create-keyboard-shortcut-in-javascript"
  status = 200

[[redirects]]
  from = "/tutorials/redux-tutorials-for-beginners"
  to = "/blog/redux-tutorials-for-beginners"
  status = 200

[[redirects]]
  from = "/tutorials/how-to-configure-vim-or-neovim-like-vscode"
  to = "/blog/how-to-configure-vim-or-neovim-like-vscode"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "aianshume"
  deliveryType = "upload"
  uploadPreset = "assets"
  imagesPath = "/public/assets"
  loadingStrategy = "lazy"